#!/usr/bin/env php
<?php

function clog($text){ echo "[*] $text\n"; }

$filename = "commvault.phar";
if(file_exists($filename)){
    unlink($filename);
}

clog("Creating Phar file ...");

$option = get_cfg_var('phar.readonly');
if($option === FALSE or in_array(strtoupper($option), ['ON', 1])){
    clog("Can't create Phar file! Set phar.readonly to Off in PHP config.");
    die();
}

$phar = new Phar($filename,
    FilesystemIterator::CURRENT_AS_FILEINFO |
    FilesystemIterator::KEY_AS_FILENAME
    , $filename);

$phar = $phar->convertToExecutable(Phar::PHAR);

clog("Adding files ...");
$phar->buildFromDirectory("src");


if(is_dir(".git")){
    $version = exec("git rev-parse HEAD");
    $version = trim($version);
    if(!empty($version)){
        clog("Adding git version ...");
        $phar->addFromString("version", $version);
    }
}

clog("Creating stub ...");
$stub = "#!/usr/bin/env php \n"
        .$phar->createDefaultStub("App.php");
$phar->setStub($stub);

$phar->stopBuffering();

clog("Giving executable perms ...");
rename($filename, "commvault");
chmod("commvault", 0555);

clog("Done! You can move the file to /usr/local/bin for global usage.");

?>
